version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    groups:
      docker-dependencies:
        patterns:
          - '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
