import { Route } from '@angular/router';
import {
  AdminBillingFacade,
  AdminCustomerProfilesFacade,
  AdminDatevExportsFacade,
  AdminInvoiceManagerFacade,
  AdminSubscriptionsFacade,
  BillingCapabilitiesFacade,
  AddonsFacade,
  addonsReducer,
  adminCustomerProfilesReducer,
  adminInvoiceManagerReducer,
  adminSubscriptionsReducer,
  adminMarkPaid$,
  adminMarkUnpaid$,
  adminVoidInvoice$,
  adminInvoiceManagerMarkPaid$,
  adminInvoiceManagerMarkUnpaid$,
  adminInvoiceManagerVoid$,
  createAdminCustomerProfile$,
  createManualInvoice$,
  deleteAdminCustomerProfile$,
  deleteManualInvoice$,
  issueManualInvoice$,
  loadAdminCustomerProfiles$,
  loadAdminCustomerProfilesBatch$,
  loadAdminCustomerProfileTrustScore$,
  loadAdminSubscriptions$,
  loadAdminSubscriptionsBatch$,
  adminCancelSubscription$,
  adminWithdrawSubscription$,
  adminInstantCancelSubscription$,
  adminResumeSubscription$,
  loadAdminInvoiceManager$,
  loadAdminInvoiceManagerBatch$,
  recomputeAdminCustomerProfileTrustScore$,
  saveAdminCustomerProfileCustomData$,
  updateAdminCustomerProfile$,
  updateManualInvoice$,
  adminBillingReducer,
  adminDatevExportsReducer,
  billingCapabilitiesReducer,
  billNow$,
  loadAdminAuditLogs$,
  loadAdminBillingSummary$,
  loadAdminOpenOverdue$,
  loadAdminStatisticsByCountry$,
  loadAdminStatisticsByProduct$,
  loadAdminStatisticsSummary$,
  AvailabilityFacade,
  availabilityReducer,
  BackordersFacade,
  backordersReducer,
  billingDashboardSocketApplicationErrorFallback$,
  BillingDashboardSocketFacade,
  billingDashboardSocketReducer,
  cancelBackorder$,
  cancelSubscription$,
  checkAvailability$,
  checkAvailabilityAlternatives$,
  connectBillingDashboardSocket$,
  connectBillingDashboardSocketFailureFallback$,
  createInvoice$,
  createServicePlan$,
  createServiceType$,
  createSubscription$,
  createAddon$,
  CloudInitConfigsFacade,
  cloudInitConfigsReducer,
  createCloudInitConfig$,
  updateCloudInitConfig$,
  deleteCloudInitConfig$,
  loadCloudInitConfigs$,
  loadCloudInitConfigsBatch$,
  loadCloudInitConfig$,
  loadAddons$,
  loadAddonsBatch$,
  loadAddon$,
  updateAddon$,
  deleteAddon$,
  CustomerProfileFacade,
  customerProfileReducer,
  deleteServicePlan$,
  deleteServiceType$,
  disconnectBillingDashboardSocket$,
  InvoicesFacade,
  invoicesReducer,
  loadBackorders$,
  loadBackordersBatch$,
  loadCustomerProfile$,
  loadInvoices$,
  loadInvoicesSummary$,
  loadInvoiceDetails$,
  loadOpenOverdueInvoices$,
  loadHistoryInvoices$,
  reloadInvoicesAfterCreate$,
  initiatePaymentRedirect$,
  loadOverviewServerInfo$,
  reloadProvisioningAfterOrder$,
  loadProviderDetails$,
  loadServicePlan$,
  loadServicePlans$,
  loadServicePlansBatch$,
  loadServiceType$,
  loadServiceTypes$,
  loadServiceTypesBatch$,
  loadSubscription$,
  loadSubscriptions$,
  loadSubscriptionsBatch$,
  previewPricing$,
  restartServer$,
  resumeSubscription$,
  retryBackorder$,
  withdrawSubscription$,
  ServicePlansFacade,
  servicePlansReducer,
  ServiceTypesFacade,
  serviceTypesReducer,
  startServer$,
  stopServer$,
  SubscriptionServerInfoFacade,
  subscriptionServerInfoReducer,
  SubscriptionsFacade,
  subscriptionsReducer,
  SubscriptionConfigChangeFacade,
  subscriptionConfigChangeReducer,
  loadConfigChangeEligibility$,
  previewConfigChange$,
  submitConfigChange$,
  updateCustomerProfile$,
  setupAutoBilling$,
  setupAutoBillingRedirect$,
  enableAutoBilling$,
  disableAutoBilling$,
  updateServicePlan$,
  updateServiceType$,
  loadBillingCapabilities$,
  loadAdminDatevExports$,
  loadAdminDatevExportsBatch$,
  triggerDatevExport$,
  triggerDatevExportSuccessReload$,
  pollQueuedDatevExports$,
  expireQueuedDatevExports$,
  downloadDatevExport$,
  ProjectsFacade,
  projectsReducer,
  loadProjects$,
  loadProjectsBatch$,
  loadProjectDetail$,
  loadProjectSummary$,
  loadAdminProjects$,
  loadAdminProjectsBatch$,
  loadAdminProjectDetail$,
  createAdminProject$,
  updateAdminProject$,
  deleteAdminProject$,
  billProjectTime$,
  ProjectTicketsFacade,
  projectTicketsReducer,
  loadProjectTickets$,
  openProjectTicketDetail$,
  createProjectTicket$,
  updateProjectTicket$,
  deleteProjectTicket$,
  addProjectTicketComment$,
  ProjectMilestonesFacade,
  projectMilestonesReducer,
  loadProjectMilestones$,
  createProjectMilestone$,
  updateProjectMilestone$,
  lockProjectMilestone$,
  deleteProjectMilestone$,
  ProjectTimeEntriesFacade,
  projectTimeEntriesReducer,
  loadProjectTimeEntries$,
  loadProjectTimeEntriesBatch$,
  loadProjectTicketTimeEntries$,
  loadProjectTicketTimeEntriesBatch$,
  loadProjectTicketTimeEntriesOnDetailOpen$,
  clearProjectTicketTimeEntriesOnDetailClose$,
  createProjectTimeEntry$,
  updateProjectTimeEntry$,
  deleteProjectTimeEntry$,
  ProjectBoardSocketFacade,
  projectBoardSocketReducer,
  connectProjectBoardSocket$,
  disconnectProjectBoardSocket$,
  restoreProjectBoardSocketProject$,
  PublicWithdrawalFacade,
  publicWithdrawalReducer,
  loadPublicWithdrawalAddressee$,
  requestPublicWithdrawal$,
  verifyPublicWithdrawalCode$,
  confirmPublicWithdrawal$,
  AdminPromotionsFacade,
  adminPromotionsReducer,
  loadAdminPromotions$,
  loadAdminPromotionsBatch$,
  createAdminPromotion$,
  updateAdminPromotion$,
  deactivateAdminPromotion$,
  loadAdminPromotionRedemptions$,
  loadAdminPromotionRedemptionsBatch$,
  PromotionsFacade,
  promotionsReducer,
  loadActivePromotions$,
  loadActivePromotionsBatch$,
  loadPromotionRedemptions$,
  loadPromotionRedemptionsBatch$,
  validatePromotion$,
  redeemPromotion$,
} from '@forepath/decabill/frontend/data-access-billing-console';
import { authGuard, adminGuard, identityAuthProviders, identityAuthRoutes } from '@forepath/identity/frontend';
import {
  createNotificationAdminRoutes,
  notificationAdminProviders,
} from '@forepath/shared/frontend/feature-notifications';
import { buildPageTitle } from '@forepath/shared/frontend/util-configuration';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';

import { AdminPromotionsPageComponent } from './admin-promotions-page/admin-promotions-page.component';
import { PromotionsPageComponent } from './promotions-page/promotions-page.component';
import { AdminBillingPageComponent } from './admin-billing-page/admin-billing-page.component';
import { AdminCustomerProfilesPageComponent } from './admin-customer-profiles-page/admin-customer-profiles-page.component';
import { AdminSubscriptionsPageComponent } from './admin-subscriptions-page/admin-subscriptions-page.component';
import { AdminDatevExportsPageComponent } from './admin-datev-exports-page/admin-datev-exports-page.component';
import { BillingConsoleContainerComponent } from './container/container.component';
import { billingAdminGuard } from './guards/billing-admin.guard';
import { datevExportEnabledGuard } from './guards/datev-export-enabled.guard';
import { publicWithdrawalAccessGuard } from './guards/public-withdrawal-access.guard';
import { InvoicesComponent } from './invoices/invoices.component';
import { OverviewComponent } from './overview/overview.component';
import { CloudInitConfigsPageComponent } from './cloud-init-configs-page/cloud-init-configs-page.component';
import { AddonsPageComponent } from './addons-page/addons-page.component';
import { ServicePlansPageComponent } from './service-plans-page/service-plans-page.component';
import { ServiceTypesPageComponent } from './service-types-page/service-types-page.component';
import { SubscriptionsComponent } from './subscriptions/subscriptions.component';
import { AdminProjectsPageComponent } from './admin-projects-page/admin-projects-page.component';
import { ProjectsPageComponent } from './projects-page/projects-page.component';
import { ProjectDetailPageComponent } from './project-detail-page/project-detail-page.component';
import { PublicWithdrawalComponent } from './public-withdrawal/public-withdrawal.component';

export const billingConsoleRoutes: Route[] = [
  {
    path: '',
    component: BillingConsoleContainerComponent,
    children: [
      {
        path: '',
        redirectTo: 'dashboard',
        pathMatch: 'full',
      },
      // Identity auth routes (login, register, password reset, email confirmation, user management)
      ...identityAuthRoutes,
      ...createNotificationAdminRoutes([authGuard, adminGuard]),
      {
        path: 'withdrawal',
        component: PublicWithdrawalComponent,
        canActivate: [publicWithdrawalAccessGuard],
        title: () => buildPageTitle($localize`:@@featurePublicWithdrawal-page:Withdrawal`),
        providers: [
          PublicWithdrawalFacade,
          provideState('publicWithdrawal', publicWithdrawalReducer),
          provideEffects({
            loadPublicWithdrawalAddressee$,
            requestPublicWithdrawal$,
            verifyPublicWithdrawalCode$,
            confirmPublicWithdrawal$,
          }),
        ],
      },
      {
        path: 'dashboard',
        pathMatch: 'full',
        canActivate: [authGuard],
        component: OverviewComponent,
        title: () => buildPageTitle($localize`:@@featureContainer-overviewPage:Overview`),
      },
      {
        path: 'subscriptions',
        canActivate: [authGuard],
        component: SubscriptionsComponent,
        title: () => buildPageTitle($localize`:@@featureContainer-subscriptionsPage:Plans`),
      },
      {
        path: 'promotions',
        canActivate: [authGuard],
        component: PromotionsPageComponent,
        title: () => buildPageTitle($localize`:@@featureContainer-promotionsPage:Promotions`),
      },
      {
        path: 'invoices',
        canActivate: [authGuard],
        component: InvoicesComponent,
        title: () => buildPageTitle($localize`:@@featureContainer-invoicesPage:Invoices`),
      },
      {
        path: 'projects',
        canActivate: [authGuard],
        children: [
          {
            path: '',
            component: ProjectsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-projectsPage:Projects`),
          },
          {
            path: ':projectId',
            children: [
              { path: '', pathMatch: 'full', redirectTo: 'board' },
              {
                path: ':tab',
                component: ProjectDetailPageComponent,
                data: { projectViewMode: 'customer' },
                title: () => buildPageTitle($localize`:@@featureContainer-projectDetailPage:Project`),
              },
            ],
          },
        ],
      },
      {
        path: 'administration',
        children: [
          {
            path: 'service-types',
            canActivate: [authGuard, billingAdminGuard],
            component: ServiceTypesPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-serviceTypesPage:Service Providers`),
          },
          {
            path: 'cloud-init-configs',
            canActivate: [authGuard, billingAdminGuard],
            component: CloudInitConfigsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-cloudInitConfigsPage:Configs`),
          },
          {
            path: 'addons',
            canActivate: [authGuard, billingAdminGuard],
            component: AddonsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-addonsPage:Addons`),
          },
          {
            path: 'service-plans',
            canActivate: [authGuard, billingAdminGuard],
            component: ServicePlansPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-servicePlansPage:Service Plans`),
          },
          {
            path: 'promotions',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminPromotionsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-adminPromotionsPage:Promotions`),
          },
          {
            path: 'billing',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminBillingPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-adminBillingPage:Billing`),
          },
          {
            path: 'customer-profiles',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminCustomerProfilesPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-adminProfilesPage:Billing Profiles`),
          },
          {
            path: 'subscriptions',
            canActivate: [authGuard, billingAdminGuard],
            component: AdminSubscriptionsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-adminSubscriptionsPage:Contracts`),
          },
          {
            path: 'projects',
            canActivate: [authGuard, billingAdminGuard],
            children: [
              {
                path: '',
                component: AdminProjectsPageComponent,
                title: () => buildPageTitle($localize`:@@featureContainer-adminProjectsPage:Projects`),
              },
              {
                path: ':projectId',
                children: [
                  { path: '', pathMatch: 'full', redirectTo: 'board' },
                  {
                    path: ':tab',
                    component: ProjectDetailPageComponent,
                    data: { projectViewMode: 'admin' },
                    title: () => buildPageTitle($localize`:@@featureContainer-adminProjectDetailPage:Project`),
                  },
                ],
              },
            ],
          },
          {
            path: 'datev-exports',
            canActivate: [authGuard, billingAdminGuard, datevExportEnabledGuard],
            component: AdminDatevExportsPageComponent,
            title: () => buildPageTitle($localize`:@@featureContainer-adminDatevExportsPage:DATEV Exports`),
          },
        ],
      },
      {
        path: '**',
        redirectTo: '',
      },
    ],
    providers: [
      ...identityAuthProviders,
      ...notificationAdminProviders,
      CloudInitConfigsFacade,
      AddonsFacade,
      SubscriptionsFacade,
      SubscriptionConfigChangeFacade,
      SubscriptionServerInfoFacade,
      BillingDashboardSocketFacade,
      ServicePlansFacade,
      ServiceTypesFacade,
      InvoicesFacade,
      AdminBillingFacade,
      AdminDatevExportsFacade,
      BillingCapabilitiesFacade,
      AdminInvoiceManagerFacade,
      AdminCustomerProfilesFacade,
      AdminSubscriptionsFacade,
      AdminPromotionsFacade,
      PromotionsFacade,
      ProjectsFacade,
      ProjectTicketsFacade,
      ProjectMilestonesFacade,
      ProjectTimeEntriesFacade,
      ProjectBoardSocketFacade,
      BackordersFacade,
      CustomerProfileFacade,
      AvailabilityFacade,
      provideState('subscriptions', subscriptionsReducer),
      provideState('subscriptionConfigChange', subscriptionConfigChangeReducer),
      provideState('servicePlans', servicePlansReducer),
      provideState('serviceTypes', serviceTypesReducer),
      provideState('cloudInitConfigs', cloudInitConfigsReducer),
      provideState('addons', addonsReducer),
      provideState('invoices', invoicesReducer),
      provideState('adminBilling', adminBillingReducer),
      provideState('billingCapabilities', billingCapabilitiesReducer),
      provideState('adminDatevExports', adminDatevExportsReducer),
      provideState('adminInvoiceManager', adminInvoiceManagerReducer),
      provideState('adminCustomerProfiles', adminCustomerProfilesReducer),
      provideState('adminSubscriptions', adminSubscriptionsReducer),
      provideState('adminPromotions', adminPromotionsReducer),
      provideState('promotions', promotionsReducer),
      provideState('projects', projectsReducer),
      provideState('projectTickets', projectTicketsReducer),
      provideState('projectMilestones', projectMilestonesReducer),
      provideState('projectTimeEntries', projectTimeEntriesReducer),
      provideState('projectBoardSocket', projectBoardSocketReducer),
      provideState('backorders', backordersReducer),
      provideState('customerProfile', customerProfileReducer),
      provideState('availability', availabilityReducer),
      provideState('subscriptionServerInfo', subscriptionServerInfoReducer),
      provideState('billingDashboardSocket', billingDashboardSocketReducer),
      provideEffects({
        loadSubscriptions$,
        loadSubscriptionsBatch$,
        loadSubscription$,
        createSubscription$,
        cancelSubscription$,
        withdrawSubscription$,
        resumeSubscription$,
        loadConfigChangeEligibility$,
        previewConfigChange$,
        submitConfigChange$,
        loadProviderDetails$,
        loadServiceTypes$,
        loadServiceTypesBatch$,
        loadServiceType$,
        createServiceType$,
        updateServiceType$,
        deleteServiceType$,
        loadCloudInitConfigs$,
        loadCloudInitConfigsBatch$,
        loadCloudInitConfig$,
        createCloudInitConfig$,
        updateCloudInitConfig$,
        deleteCloudInitConfig$,
        loadAddons$,
        loadAddonsBatch$,
        loadAddon$,
        createAddon$,
        updateAddon$,
        deleteAddon$,
        loadServicePlans$,
        loadServicePlansBatch$,
        loadServicePlan$,
        createServicePlan$,
        updateServicePlan$,
        deleteServicePlan$,
        loadInvoices$,
        loadInvoicesSummary$,
        loadOpenOverdueInvoices$,
        loadHistoryInvoices$,
        createInvoice$,
        reloadInvoicesAfterCreate$,
        loadInvoiceDetails$,
        initiatePaymentRedirect$,
        loadBackorders$,
        loadBackordersBatch$,
        retryBackorder$,
        cancelBackorder$,
        loadCustomerProfile$,
        updateCustomerProfile$,
        setupAutoBilling$,
        setupAutoBillingRedirect$,
        enableAutoBilling$,
        disableAutoBilling$,
        checkAvailability$,
        checkAvailabilityAlternatives$,
        previewPricing$,
        loadOverviewServerInfo$,
        reloadProvisioningAfterOrder$,
        startServer$,
        stopServer$,
        restartServer$,
        connectBillingDashboardSocket$,
        disconnectBillingDashboardSocket$,
        connectBillingDashboardSocketFailureFallback$,
        billingDashboardSocketApplicationErrorFallback$,
        loadAdminBillingSummary$,
        billNow$,
        loadAdminOpenOverdue$,
        adminVoidInvoice$,
        adminMarkPaid$,
        adminMarkUnpaid$,
        loadAdminStatisticsSummary$,
        loadAdminStatisticsByProduct$,
        loadAdminStatisticsByCountry$,
        loadAdminAuditLogs$,
        loadAdminInvoiceManager$,
        loadAdminInvoiceManagerBatch$,
        createManualInvoice$,
        updateManualInvoice$,
        issueManualInvoice$,
        deleteManualInvoice$,
        adminInvoiceManagerVoid$,
        adminInvoiceManagerMarkPaid$,
        adminInvoiceManagerMarkUnpaid$,
        loadAdminCustomerProfiles$,
        loadAdminCustomerProfilesBatch$,
        loadAdminCustomerProfileTrustScore$,
        recomputeAdminCustomerProfileTrustScore$,
        saveAdminCustomerProfileCustomData$,
        loadAdminSubscriptions$,
        loadAdminSubscriptionsBatch$,
        adminCancelSubscription$,
        adminWithdrawSubscription$,
        adminInstantCancelSubscription$,
        adminResumeSubscription$,
        loadBillingCapabilities$,
        loadAdminDatevExports$,
        loadAdminDatevExportsBatch$,
        triggerDatevExport$,
        triggerDatevExportSuccessReload$,
        pollQueuedDatevExports$,
        expireQueuedDatevExports$,
        downloadDatevExport$,
        createAdminCustomerProfile$,
        updateAdminCustomerProfile$,
        deleteAdminCustomerProfile$,
        loadAdminPromotions$,
        loadAdminPromotionsBatch$,
        createAdminPromotion$,
        updateAdminPromotion$,
        deactivateAdminPromotion$,
        loadAdminPromotionRedemptions$,
        loadAdminPromotionRedemptionsBatch$,
        loadActivePromotions$,
        loadActivePromotionsBatch$,
        loadPromotionRedemptions$,
        loadPromotionRedemptionsBatch$,
        validatePromotion$,
        redeemPromotion$,
        loadProjects$,
        loadProjectsBatch$,
        loadProjectDetail$,
        loadProjectSummary$,
        loadAdminProjects$,
        loadAdminProjectsBatch$,
        loadAdminProjectDetail$,
        createAdminProject$,
        updateAdminProject$,
        deleteAdminProject$,
        billProjectTime$,
        loadProjectTickets$,
        openProjectTicketDetail$,
        createProjectTicket$,
        updateProjectTicket$,
        deleteProjectTicket$,
        addProjectTicketComment$,
        loadProjectMilestones$,
        createProjectMilestone$,
        updateProjectMilestone$,
        lockProjectMilestone$,
        deleteProjectMilestone$,
        loadProjectTimeEntries$,
        loadProjectTimeEntriesBatch$,
        loadProjectTicketTimeEntries$,
        loadProjectTicketTimeEntriesBatch$,
        loadProjectTicketTimeEntriesOnDetailOpen$,
        clearProjectTicketTimeEntriesOnDetailClose$,
        createProjectTimeEntry$,
        updateProjectTimeEntry$,
        deleteProjectTimeEntry$,
        connectProjectBoardSocket$,
        disconnectProjectBoardSocket$,
        restoreProjectBoardSocketProject$,
      }),
      provideMonacoEditor(),
    ],
  },
];
