import { Route } from '@angular/router';
import {
  addClientUser$,
  addTicketComment$,
  AgentsFacade,
  agentsReducer,
  approveTicketAutomation$,
  AtlassianContextImportFacade,
  atlassianContextImportReducer,
  cancelRun$,
  cancelTicketAutomationRun$,
  clearExternalImportMarkers$,
  ClientAgentAutonomyFacade,
  clientAgentAutonomyReducer,
  ClientsFacade,
  clientsReducer,
  commit$,
  connectKnowledgeBoardSocket$,
  connectNotificationsSocket$,
  connectSocket$,
  connectTicketsBoardSocket$,
  createAtlassianConnection$,
  createBranch$,
  createClient$,
  createClientAgent$,
  createDeploymentConfiguration$,
  createEnvironmentVariable$,
  createChatSession$,
  createExternalImportConfig$,
  createFileOrDirectory$,
  createFilterRule$,
  createKnowledgeNode$,
  createKnowledgeRelation$,
  createTicket$,
  deleteAllEnvironmentVariables$,
  deleteAtlassianConnection$,
  deleteBranch$,
  deleteClient$,
  deleteClientAgent$,
  deleteChatSession$,
  deleteDeploymentConfiguration$,
  deleteEnvironmentVariable$,
  deleteExternalImportConfig$,
  deleteFileOrDirectory$,
  deleteFilterRule$,
  deleteKnowledgeNode$,
  deleteKnowledgeRelation$,
  deleteProvisionedServer$,
  deleteTicket$,
  deleteWorkspaceConfigurationOverride$,
  DeploymentsFacade,
  deploymentsReducer,
  disconnectKnowledgeBoardSocket$,
  disconnectNotificationsSocket$,
  disconnectSocket$,
  disconnectTicketsBoardSocket$,
  duplicateKnowledgeNode$,
  EnvFacade,
  envReducer,
  ChatSessionsFacade,
  chatSessionsReducer,
  fetch$,
  FilesFacade,
  filesReducer,
  FilterRulesFacade,
  filterRulesReducer,
  KnowledgeBoardSocketFacade,
  knowledgeBoardSocketReducer,
  KnowledgeFacade,
  knowledgeReducer,
  listDirectory$,
  loadAtlassianContextImport$,
  loadAtlassianContextImportBatch$,
  loadAtlassianConnections$,
  loadExternalImportConfigsList$,
  loadBranches$,
  loadClient$,
  loadClientAgent$,
  loadClientAgentAutonomy$,
  loadClientAgentCommandsFromFiles$,
  loadClientAgentCommandsLoading$,
  loadClientAgentModels$,
  loadClientAgents$,
  loadMoreClientAgents$,
  loadClients$,
  loadMoreClients$,
  loadClientStatisticsChatIo$,
  loadClientStatisticsEntityEvents$,
  loadClientStatisticsFilterDrops$,
  loadClientStatisticsFilterFlags$,
  loadClientStatisticsSummary$,
  loadClientUsers$,
  loadDeploymentConfiguration$,
  loadEnvironmentVariables$,
  loadEnvironmentVariablesBatch$,
  loadEnvironmentVariablesCount$,
  loadChatSessions$,
  loadFilterRules$,
  loadMoreFilterRules$,
  loadGitBranches$,
  loadGitDiff$,
  loadGitStatus$,
  loadJobLogs$,
  loadKnowledgeActivity$,
  loadKnowledgeRelations$,
  loadKnowledgeTree$,
  loadProvisioningProviders$,
  loadRepositories$,
  loadRunJobs$,
  loadRunLogs$,
  loadRuns$,
  loadRunStatus$,
  loadServerInfo$,
  loadServerInfoAfterProvisioning$,
  loadServerTypes$,
  loadLocations$,
  loadStatisticsChatIo$,
  loadStatisticsEntityEvents$,
  loadStatisticsFilterDrops$,
  loadStatisticsFilterFlags$,
  loadStatisticsSummary$,
  loadTicketAutomation$,
  loadTicketAutomationRunDetail$,
  loadTicketAutomationRuns$,
  loadTickets$,
  loadWorkflows$,
  loadWorkspaceConfigurationOverrides$,
  markEnvironmentRead$,
  migrateTicket$,
  moveFileOrDirectory$,
  NotificationsFacade,
  notificationsReducer,
  openTicketDetail$,
  patchTicketAutomation$,
  playUnreadNotificationSound$,
  playUnreadSoundEffect$,
  processContainerStats$,
  provisionServer$,
  pull$,
  push$,
  readFile$,
  rebase$,
  refreshTicketDetailActivityAfterAutomation$,
  reloadActivityAfterWrite$,
  reloadRelationsAfterWrite$,
  reloadTreeAfterWrite$,
  reloadWorkspaceConfigurationAfterMutation$,
  removeClientUser$,
  resolveConflict$,
  restartClientAgent$,
  restoreAgentLogin$,
  restoreClientContext$,
  restoreKnowledgeBoardSocketClient$,
  restoreTicketsBoardSocketClient$,
  runExternalImportConfig$,
  setActiveClient$,
  setActiveEnvironment$,
  SocketsFacade,
  socketsReducer,
  stageFiles$,
  startClientAgent$,
  StatisticsFacade,
  statisticsReducer,
  StatsFacade,
  statsReducer,
  stopClientAgent$,
  switchBranch$,
  syncTicketAutomationRunFromClientsChat$,
  syncTicketsFromClientsChatTicketUpsert$,
  testAtlassianConnection$,
  TicketAutomationFacade,
  ticketAutomationReducer,
  TicketsBoardSocketFacade,
  ticketsBoardSocketReducer,
  TicketsFacade,
  ticketsReducer,
  triggerWorkflow$,
  unapproveTicketAutomation$,
  unstageFiles$,
  updateAtlassianConnection$,
  updateClient$,
  updateClientAgent$,
  updateChatSession$,
  updateDeploymentConfiguration$,
  updateEnvironmentVariable$,
  updateExternalImportConfig$,
  updateFilterRule$,
  updateKnowledgeNode$,
  updateTicket$,
  upsertClientAgentAutonomy$,
  upsertWorkspaceConfigurationOverride$,
  VcsFacade,
  vcsReducer,
  WorkspaceConfigFacade,
  workspaceConfigReducer,
  writeFile$,
} from '@forepath/agenstra/frontend/data-access-agent-console';
import { adminGuard, authGuard, identityAuthProviders, identityAuthRoutes } from '@forepath/identity/frontend';
import {
  createNotificationAdminRoutes,
  notificationAdminProviders,
} from '@forepath/shared/frontend/feature-notifications';
import { createUpdatesAdminRoutes, updatesAdminProviders } from '@forepath/shared/frontend/feature-updates';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';

import { AtlassianImportAdminComponent } from './atlassian-import-admin/atlassian-import-admin.component';
import { AuditComponent } from './audit/audit.component';
import { AgentConsoleChatComponent } from './chat/chat.component';
import { AgentConsoleContainerComponent } from './container/container.component';
import { configEditorGuard } from './guards/config-editor.guard';
import { ticketsRequireActiveClientGuard } from './guards/tickets-require-active-client.guard';
import { KnowledgeBoardComponent } from './knowledge/knowledge-board.component';
import { RuleManagerComponent } from './rule-manager/rule-manager.component';
import { provideAgenstraNotificationAdminClientProvider } from './providers/notification-admin.providers';
import { TicketsBoardComponent } from './tickets/tickets-board.component';

export const agentConsoleRoutes: Route[] = [
  {
    path: '',
    component: AgentConsoleContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'clients',
      },
      // Identity auth routes (login, register, password reset, email confirmation, user management)
      ...identityAuthRoutes,
      ...createNotificationAdminRoutes([authGuard, adminGuard]),
      ...createUpdatesAdminRoutes([authGuard, adminGuard]),
      {
        path: 'audit',
        canActivate: [authGuard],
        component: AuditComponent,
        title: $localize`:@@featureAgentConsole-auditTitle:Audit :: Agenstra`,
      },
      {
        path: 'filters',
        canActivate: [authGuard, adminGuard],
        component: RuleManagerComponent,
        title: $localize`:@@featureAgentConsole-filtersTitle:Filters :: Agenstra`,
      },
      {
        path: 'imports/atlassian',
        canActivate: [authGuard, adminGuard],
        component: AtlassianImportAdminComponent,
        title: $localize`:@@featureAgentConsole-atlassianImportTitle:Atlassian import :: Agenstra`,
      },
      {
        path: 'tickets/:clientId',
        canActivate: [authGuard, ticketsRequireActiveClientGuard],
        component: TicketsBoardComponent,
        title: $localize`:@@featureAgentConsole-ticketsTitle:Tickets :: Agenstra`,
      },
      {
        path: 'tickets',
        canActivate: [authGuard, ticketsRequireActiveClientGuard],
        component: TicketsBoardComponent,
        title: $localize`:@@featureAgentConsole-ticketsTitle:Tickets :: Agenstra`,
      },
      {
        path: 'knowledge/:clientId',
        canActivate: [authGuard, ticketsRequireActiveClientGuard],
        component: KnowledgeBoardComponent,
        title: $localize`:@@featureAgentConsole-knowledgeTitle:Knowledge :: Agenstra`,
      },
      {
        path: 'knowledge',
        canActivate: [authGuard, ticketsRequireActiveClientGuard],
        component: KnowledgeBoardComponent,
        title: $localize`:@@featureAgentConsole-knowledgeTitle:Knowledge :: Agenstra`,
      },
      {
        path: 'clients',
        canActivate: [authGuard],
        title: $localize`:@@featureAgentConsole-managerTitle:Manager :: Agenstra`,
        children: [
          {
            path: '',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/editor',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/config',
            canActivate: [authGuard, configEditorGuard],
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/deployments',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
        ],
      },
      {
        path: '**',
        redirectTo: 'clients',
      },
    ],
    providers: [
      // Identity auth state (authentication reducer, facade, and auth effects)
      ...identityAuthProviders,
      ...notificationAdminProviders,
      ...updatesAdminProviders,
      provideAgenstraNotificationAdminClientProvider(),
      // Facades
      AgentsFacade,
      ClientsFacade,
      SocketsFacade,
      TicketsBoardSocketFacade,
      KnowledgeBoardSocketFacade,
      FilesFacade,
      EnvFacade,
      ChatSessionsFacade,
      VcsFacade,
      StatsFacade,
      StatisticsFacade,
      DeploymentsFacade,
      TicketsFacade,
      TicketAutomationFacade,
      KnowledgeFacade,
      ClientAgentAutonomyFacade,
      FilterRulesFacade,
      AtlassianContextImportFacade,
      WorkspaceConfigFacade,
      NotificationsFacade,
      // Feature states - registered at feature level for lazy loading
      provideState('clients', clientsReducer),
      provideState('agents', agentsReducer),
      provideState('sockets', socketsReducer),
      provideState('ticketsBoardSocket', ticketsBoardSocketReducer),
      provideState('knowledgeBoardSocket', knowledgeBoardSocketReducer),
      provideState('files', filesReducer),
      provideState('env', envReducer),
      provideState('chatSessions', chatSessionsReducer),
      provideState('vcs', vcsReducer),
      provideState('stats', statsReducer),
      provideState('statistics', statisticsReducer),
      provideState('deployments', deploymentsReducer),
      provideState('tickets', ticketsReducer),
      provideState('ticketAutomation', ticketAutomationReducer),
      provideState('knowledge', knowledgeReducer),
      provideState('clientAgentAutonomy', clientAgentAutonomyReducer),
      provideState('filterRules', filterRulesReducer),
      provideState('atlassianContextImport', atlassianContextImportReducer),
      provideState('workspaceConfig', workspaceConfigReducer),
      provideState('notifications', notificationsReducer),
      // Effects - only active when this feature route is loaded
      provideEffects({
        loadClients$,
        loadMoreClients$,
        loadClient$,
        loadClientAgentAutonomy$,
        loadClientUsers$,
        addClientUser$,
        removeClientUser$,
        createClient$,
        updateClient$,
        deleteClient$,
        setActiveClient$,
        loadProvisioningProviders$,
        loadServerTypes$,
        loadLocations$,
        provisionServer$,
        loadServerInfo$,
        loadServerInfoAfterProvisioning$,
        deleteProvisionedServer$,
        loadClientAgents$,
        loadMoreClientAgents$,
        loadClientAgent$,
        loadClientAgentModels$,
        loadClientAgentCommandsLoading$,
        loadClientAgentCommandsFromFiles$,
        createClientAgent$,
        updateClientAgent$,
        deleteClientAgent$,
        startClientAgent$,
        stopClientAgent$,
        restartClientAgent$,
        connectSocket$,
        disconnectSocket$,
        restoreClientContext$,
        restoreAgentLogin$,
        connectKnowledgeBoardSocket$,
        connectNotificationsSocket$,
        disconnectKnowledgeBoardSocket$,
        disconnectNotificationsSocket$,
        markEnvironmentRead$,
        setActiveEnvironment$,
        playUnreadNotificationSound$,
        playUnreadSoundEffect$,
        restoreKnowledgeBoardSocketClient$,
        syncTicketAutomationRunFromClientsChat$,
        syncTicketsFromClientsChatTicketUpsert$,
        connectTicketsBoardSocket$,
        disconnectTicketsBoardSocket$,
        restoreTicketsBoardSocketClient$,
        readFile$,
        writeFile$,
        listDirectory$,
        createFileOrDirectory$,
        deleteFileOrDirectory$,
        moveFileOrDirectory$,
        loadEnvironmentVariables$,
        loadEnvironmentVariablesBatch$,
        loadEnvironmentVariablesCount$,
        createEnvironmentVariable$,
        updateEnvironmentVariable$,
        deleteEnvironmentVariable$,
        deleteAllEnvironmentVariables$,
        loadChatSessions$,
        createChatSession$,
        updateChatSession$,
        deleteChatSession$,
        loadGitStatus$,
        loadGitBranches$,
        loadGitDiff$,
        stageFiles$,
        unstageFiles$,
        commit$,
        push$,
        pull$,
        fetch$,
        rebase$,
        switchBranch$,
        createBranch$,
        deleteBranch$,
        resolveConflict$,
        processContainerStats$,
        loadClientStatisticsSummary$,
        loadClientStatisticsChatIo$,
        loadClientStatisticsFilterDrops$,
        loadClientStatisticsFilterFlags$,
        loadClientStatisticsEntityEvents$,
        loadStatisticsSummary$,
        loadStatisticsChatIo$,
        loadStatisticsFilterDrops$,
        loadStatisticsFilterFlags$,
        loadStatisticsEntityEvents$,
        loadDeploymentConfiguration$,
        createDeploymentConfiguration$,
        updateDeploymentConfiguration$,
        deleteDeploymentConfiguration$,
        loadRepositories$,
        loadBranches$,
        loadWorkflows$,
        loadRuns$,
        triggerWorkflow$,
        loadRunStatus$,
        loadRunLogs$,
        cancelRun$,
        loadRunJobs$,
        loadJobLogs$,
        loadTickets$,
        openTicketDetail$,
        createTicket$,
        updateTicket$,
        migrateTicket$,
        deleteTicket$,
        addTicketComment$,
        loadTicketAutomation$,
        patchTicketAutomation$,
        refreshTicketDetailActivityAfterAutomation$,
        approveTicketAutomation$,
        unapproveTicketAutomation$,
        loadTicketAutomationRuns$,
        loadTicketAutomationRunDetail$,
        cancelTicketAutomationRun$,
        loadKnowledgeTree$,
        loadKnowledgeRelations$,
        loadKnowledgeActivity$,
        createKnowledgeNode$,
        createKnowledgeRelation$,
        updateKnowledgeNode$,
        duplicateKnowledgeNode$,
        deleteKnowledgeNode$,
        deleteKnowledgeRelation$,
        reloadTreeAfterWrite$,
        reloadRelationsAfterWrite$,
        reloadActivityAfterWrite$,
        upsertClientAgentAutonomy$,
        loadFilterRules$,
        loadMoreFilterRules$,
        createFilterRule$,
        updateFilterRule$,
        deleteFilterRule$,
        loadAtlassianContextImport$,
        loadAtlassianContextImportBatch$,
        loadAtlassianConnections$,
        loadExternalImportConfigsList$,
        createAtlassianConnection$,
        updateAtlassianConnection$,
        deleteAtlassianConnection$,
        testAtlassianConnection$,
        createExternalImportConfig$,
        updateExternalImportConfig$,
        deleteExternalImportConfig$,
        runExternalImportConfig$,
        clearExternalImportMarkers$,
        loadWorkspaceConfigurationOverrides$,
        upsertWorkspaceConfigurationOverride$,
        deleteWorkspaceConfigurationOverride$,
        reloadWorkspaceConfigurationAfterMutation$,
      }),
      provideMonacoEditor(),
    ],
  },
];
