import { Route } from '@angular/router';
import {
  AgentsFacade,
  agentsReducer,
  authenticationReducer,
  checkAuthentication$,
  ClientsFacade,
  clientsReducer,
  commit$,
  connectSocket$,
  createBranch$,
  createClient$,
  createClientAgent$,
  createFileOrDirectory$,
  deleteBranch$,
  deleteClient$,
  deleteClientAgent$,
  deleteFileOrDirectory$,
  deleteProvisionedServer$,
  disconnectSocket$,
  fetch$,
  FilesFacade,
  filesReducer,
  listDirectory$,
  loadClient$,
  loadClientAgent$,
  loadClientAgentCommandsFromFiles$,
  loadClientAgentCommandsLoading$,
  loadClientAgents$,
  loadClientAgentsBatch$,
  loadClients$,
  loadClientsBatch$,
  loadGitBranches$,
  loadGitDiff$,
  loadGitStatus$,
  loadProvisioningProviders$,
  loadServerInfo$,
  loadServerInfoAfterProvisioning$,
  loadServerTypes$,
  login$,
  loginSuccessRedirect$,
  logout$,
  logoutSuccessRedirect$,
  moveFileOrDirectory$,
  provisionServer$,
  pull$,
  push$,
  readFile$,
  rebase$,
  resolveConflict$,
  setActiveClient$,
  SocketsFacade,
  socketsReducer,
  stageFiles$,
  switchBranch$,
  unstageFiles$,
  updateClient$,
  updateClientAgent$,
  VcsFacade,
  vcsReducer,
  writeFile$,
} from '@forepath/framework/frontend/data-access-agent-console';
import { provideEffects } from '@ngrx/effects';
import { provideState } from '@ngrx/store';
import { provideMonacoEditor } from 'ngx-monaco-editor-v2';
import { AgentConsoleChatComponent } from './chat/chat.component';
import { AgentConsoleContainerComponent } from './container/container.component';
import { authGuard } from './guards/auth.guard';
import { loginGuard } from './guards/login.guard';
import { AgentConsoleLoginComponent } from './login/login.component';

export const agentConsoleRoutes: Route[] = [
  {
    path: '',
    component: AgentConsoleContainerComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'clients',
      },
      {
        path: 'login',
        component: AgentConsoleLoginComponent,
        canActivate: [loginGuard],
        title: 'Login | Agenstra',
      },
      {
        path: 'clients',
        canActivate: [authGuard],
        title: 'Manager | Agenstra',
        children: [
          {
            path: '',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
          {
            path: ':clientId/agents/:agentId/editor',
            component: AgentConsoleChatComponent,
            pathMatch: 'full',
          },
        ],
      },
      {
        path: '**',
        redirectTo: 'clients',
      },
    ],
    providers: [
      // Facades
      AgentsFacade,
      ClientsFacade,
      SocketsFacade,
      FilesFacade,
      VcsFacade,
      // Feature states - registered at feature level for lazy loading
      provideState('clients', clientsReducer),
      provideState('agents', agentsReducer),
      provideState('sockets', socketsReducer),
      provideState('authentication', authenticationReducer),
      provideState('files', filesReducer),
      provideState('vcs', vcsReducer),
      // Effects - only active when this feature route is loaded
      provideEffects({
        loadClients$,
        loadClientsBatch$,
        loadClient$,
        createClient$,
        updateClient$,
        deleteClient$,
        setActiveClient$,
        loadProvisioningProviders$,
        loadServerTypes$,
        provisionServer$,
        loadServerInfo$,
        loadServerInfoAfterProvisioning$,
        deleteProvisionedServer$,
        loadClientAgents$,
        loadClientAgentsBatch$,
        loadClientAgent$,
        loadClientAgentCommandsLoading$,
        loadClientAgentCommandsFromFiles$,
        createClientAgent$,
        updateClientAgent$,
        deleteClientAgent$,
        connectSocket$,
        disconnectSocket$,
        login$,
        loginSuccessRedirect$,
        logout$,
        logoutSuccessRedirect$,
        checkAuthentication$,
        readFile$,
        writeFile$,
        listDirectory$,
        createFileOrDirectory$,
        deleteFileOrDirectory$,
        moveFileOrDirectory$,
        loadGitStatus$,
        loadGitBranches$,
        loadGitDiff$,
        stageFiles$,
        unstageFiles$,
        commit$,
        push$,
        pull$,
        fetch$,
        rebase$,
        switchBranch$,
        createBranch$,
        deleteBranch$,
        resolveConflict$,
      }),
      provideMonacoEditor(),
    ],
  },
];
