name: Setup Environment
description: Setup environment variables for the GitHub Actions workflow.

runs:
  using: 'composite'
  steps:
    - name: Setup Node from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Enable corepack
      shell: bash
      run: corepack enable || true

    - name: Detect package manager
      id: pm
      shell: bash
      run: |
        if [ -f pnpm-lock.yaml ]; then echo "pm=pnpm" >> $GITHUB_OUTPUT; exit 0; fi
        if [ -f yarn.lock ]; then echo "pm=yarn" >> $GITHUB_OUTPUT; exit 0; fi
        if [ -f package-lock.json ]; then echo "pm=npm" >> $GITHUB_OUTPUT; exit 0; fi
        echo "pm=pnpm" >> $GITHUB_OUTPUT

    - name: Install dependencies
      shell: bash
      run: |
        PM="${{ steps.pm.outputs.pm }}"
        if [ "$PM" = "pnpm" ]; then pnpm install --frozen-lockfile; fi
        if [ "$PM" = "yarn" ]; then yarn install --frozen-lockfile; fi
        if [ "$PM" = "npm" ]; then npm ci; fi

    - name: Set Cypress cache folder
      id: cypress-cache
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          CYPRESS_CACHE="$USERPROFILE/.cache/Cypress"
        else
          CYPRESS_CACHE="$HOME/.cache/Cypress"
        fi
        echo "folder=$CYPRESS_CACHE" >> $GITHUB_OUTPUT
        echo "CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE" >> $GITHUB_ENV

    - name: Restore Cypress cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.cypress-cache.outputs.folder }}
          node_modules/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml', '**/yarn.lock', '**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-

    - name: Cypress binary install
      shell: bash
      env:
        CYPRESS_CACHE_FOLDER: ${{ steps.cypress-cache.outputs.folder }}
      run: |
        PM="${{ steps.pm.outputs.pm }}"
        if [ "$PM" = "pnpm" ]; then pnpm exec cypress install || true; fi
        if [ "$PM" = "yarn" ]; then yarn run -s cypress install || yarn dlx cypress install || true; fi
        if [ "$PM" = "npm" ]; then npx --yes cypress install || true; fi

    - name: Electron binary install
      shell: bash
      working-directory: ./node_modules/electron
      run: npm run postinstall || node install.js || true
