import { IDENTITY_NOTIFICATION_EVENTS } from '@forepath/identity/backend';

export const BILLING_NOTIFICATION_EVENTS = [
  ...IDENTITY_NOTIFICATION_EVENTS,
  'invoice.created',
  'invoice.issued',
  'invoice.voided',
  'invoice.tax_mode_applied',
  'payment.initiated',
  'payment.succeeded',
  'payment.failed',
  'payment.auto.initiated',
  'payment.auto.retry_scheduled',
  'payment.auto.exhausted',
  'auto_billing.enabled',
  'auto_billing.disabled',
  'payment_method.attached',
  'customer_trust.level_changed',
  'vat_id.validation_succeeded',
  'vat_id.validation_failed',
  'vat_id.validation_pending',
  'vat_id.validation_unavailable',
  'oss.threshold_exceeded',
  'subscription.created',
  'subscription.updated',
  'subscription.cancel_scheduled',
  'subscription.canceled',
  'subscription.resumed',
  'subscription.period_charged',
  'subscription.config_change_requested',
  'subscription.config_changed',
  'subscription.config_change_failed',
  'subscription.ssh_access_granted',
  'service_plan.price_recalculated',
  'subscription.price_changed',
  'addon.activated',
  'addon.deactivated',
  'addon.provision_failed',
  'addon.teardown_failed',
  'project.created',
  'project.updated',
  'project.deleted',
  'milestone.created',
  'milestone.updated',
  'milestone.deleted',
  'time_entry.created',
  'time_entry.updated',
  'time_entry.deleted',
  'ticket.created',
  'ticket.updated',
  'ticket.deleted',
  'ticket.comment.created',
  'datev_export.started',
  'datev_export.completed',
  'datev_export.failed',
] as const;

export type BillingNotificationEventType = (typeof BILLING_NOTIFICATION_EVENTS)[number];
